{% set name = "fastexcel" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ToucanToco/fastexcel/archive/v{{ version }}.tar.gz
  sha256: 89944eb0a6aa278dfc19251b56934327ec6f1b4046d0ae722ff8658a5b2e5487

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 3

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.3.2,<2.0                   # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.3.2,<2.0
    - pip
  run:
    - python
    - pyarrow >=8.0.0
    - typing-extensions >=4.0.0  # [py<310]
  run_constrained:
    - pandas >=1.4.4
    - polars >=0.16.14

test:
  imports:
    - fastexcel
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A fast excel file reader for Python, written in Rust.
  home: https://github.com/ToucanToco/fastexcel
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - arnabanimesh
    - borchero
